### ISSUE TITLE
Quick connect from the launcher

### ISSUE THREAD

**Issue by VShawn** [1Remote/PRemoteM#313]
![image](https://user-images.githubusercontent.com/10143738/181450850-7cb8d6a1-589a-40c7-8d4c-a016fd45a9ce.png)

Actually I have a plan like the picture above for a long time. What stopping me is that I've not found a snappy approach to enter username & password for the `quick connect`.

OTOH, It will break the sessions control logic based on database id if we import `quick connect`.

_Originally posted by @VShawn in https://github.com/1Remote/PRemoteM/issues/273#issuecomment-1197797368_
 

- [x] divide launcher view to `session search view` and `quick connect view`
- [x] press tab key to toggle quick connect in the launcher
- [x] support create connection from a non-existent session
- [x] add popup to acquire password
- ~inherit password form existing session~
- [x] show quick connect history (remember host and protocol only)
- [x] oepn connect from history (ask for password again since pws not saved)
- ~ask `do you want to save this session?` when close session.~ Bad UX

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/200113301-c222d345-0564-462d-bec5-3afa98b6977a.png)

![image](https://user-images.githubusercontent.com/10143738/200113370-608c03f2-1355-404e-ad30-dbbaa7f9249a.png)

almost done
